# -*- coding: utf-8 -*-
"""aula_exercicios_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ijkmAghcwvv09TLcyRdk5IjLXjj5lg7l

## Exercício 1: Verifique se um número é positivo, negativo ou zero.
"""

#Verifique o(s) número(s) apresentados;
#Verique se há sinal de negativo(-) ou não e não é zero (0);
#Se houver e não for zero (0), diga que é positivo;
#Se não, diga que é negativo;
#Se for zero diga que é zero.
#Se for zero diga que é zero.

num = int(input('Digite um número: '))
if num > 0:
  print('Positivo')
elif num < 0:
  print('Negativo')
else:
  print('Zero')

"""## Exercício 2: Peça dois números e exiba o maior."""

#Verifique os dois números apresentados;
#Calcule qual deles é o menor e qual é o maior;
#Apresente o maior no resultado.

num1 = int(input('Digite o primeiro número: '))
num2 = int(input('Digite o segundo número: '))

if num1 > num2:
  print('O número maior é ', num1)
elif num1 == num2:
  print('Os números são iguais.')
else:
  print('O número maior é ', num2)

"""## Exercício 3: Verifique se um número é par ou ímpar."""

#Verifique o(s) número(s) apresentados;
#Faça a divisão de cada um por 2;
#Se o resultado for um número inteiro diga que é par;
#Se for um número decimal, que é ímpar.

num = int(input('Digite um número: '))
if num % 2 == 0:
  print('Par')
else:
  print('Ímpar')

"""## Exercício 4: Verifique se um ano é bissexto."""

#Verifique o ano apresentado;
#Com base no histórico de anos bissextos (de 4 em 4 anos), calcule se este é um deles.

ano = int(input('Digite um ano com 4 digitos: '))
if (ano % 4 == 0 and ano % 100 != 0) or ano % 400 == 0:
  print('É bissexto')
else:
  print('Não é bissexto')

"""## Exercício 5: Peça três números e exiba o maior."""

#Verifique os 3 números apresentados;
#Compare-os e calcule qual dele possui o maior valor;
#Apresente o maior no resultado.

num1 = int(input('Digite o primeiro número: '))
num2 = int(input('Digite o segundo número: '))
num3 = int(input('Digite o terceiro número: '))
print('O número maior é ', max(num1, num2, num3))

"""## Exercício 6: Verifique se um usuário pode votar (idade >= 18)."""

#Verifique o número da idade realacionada ao usuário;
#Se for maior ou igual à 18, diga que pode votar;
#Se for menor que 18, diga que não pode.

num = int(input('Informe a idade: '))
if num >= 18:
  print('Pode votar')
else:
  print('Não pode votar')

"""## Exercício 7: Verifique se já posso ir embora da aula de Análise de Dados sem assinar a folha."""

#Verique que horas são;
#Verifique se tenho alguma urgência;
#Verifique se não tenho nada a perder;
#se for mais de 22h, diga que posso ir;
#se não for, diga que não posso;

from datetime import datetime, time

print(datetime.now().time())
if datetime.now().time() >= time(00,45,0):
  print('Pode')
else:
  print('Não pode')

"""## Exercício 8: Verifique se uma senha digitada corresponde a '1234'."""

senha = input('Digite sua senha: ')

if senha == '1234':
  print('Senha correta')
else:
  print('Senha incorreta')

"""## Exercício 9: Verifique se um número está entre 10 e 50."""

num = int(input('Digite um número: '))
if num >= 10 and num <= 50:
  print('O valor está entre 10 e 50')
else:
  print('O valor não está entre 10 e 50')

"""## Exercício 10: Peça ao usuário um número e exiba 'Alto' se for maior que 100 e 'Baixo' se for menor."""

num = int(input('Digite um número: '))
if num >= 100:
  print('Alto')
else:
  print('Baixo')

"""## Exercício 11: Crie um menu onde o usuário pode escolher entre somar, subtrair, multiplicar e dividir dois números."""

def operacao(op, a, b):
  return {
      '1': a + b,
      '2': a - b,
      '3': a * b,
      '4': a / b
  if b != 0
  else 'Divisão por zero não aceita'
  }.get(op, 'Operação inválida!')

op = input('Escolha: 1-Soma, 2-Sub, 3-Mult, 4-Div: ')
# a, b = map(int, input('Digite dois números: ').split())
print('Resultado: ', operacao(op, a, b))

"""## Exercício 12: Crie um menu para converter temperaturas entre Celsius, Fahrenheit e Kelvin."""

def conversao(t,temp):
  return {
      'F': (temp *9/5) +32 ,
      'K': (temp + 273)

  }.get(t,'Conversão não encontrada')

t = input('Digite a escala de temperatura F/K: ')
temp = float(input('Digite o valor da temperatura: '))
print(conversao(t,temp))

"""## Exercício 13: Crie um programa que traduza números de 1 a 5 para palavras (1 = um, 2 = dois...)."""

def traducao(num):
  return {
      '1': "um",
      '2': "dois",
      '3': "três",
      '4': "quatro",
      '5': "cinco"

  }.get(num, 'não encontrado')

num = input('Digite um número de 1 a 5: ')
print(traducao(num))

"""## Exercício 14: Crie um menu onde o usuário pode escolher entre exibir a data, hora ou sair."""

from datetime import datetime, time, date

op = input('1-Data\n2-Hora\n3-Sair\nEscolha uma das opções: ')
print({
    '1': datetime.now().date(),
    '2': datetime.now().time(),
    '3': 'Saindo'

    }.get(op, 'Opção inválida'))

from datetime import datetime, time, date
hora = input('Digite um número')
{
    'hora': datetime.now().time(),
    'data': datetime.now().date(),
    'sair': f'saindo do programa'
}
 print(hora.get('hora','não encontrado'))

"""## Exercício 15: Implemente um programa que identifica o dia da semana baseado em um número (1 = Segunda, 7 = Domingo)."""

def diasemana(num):
  return {
      '1': "segunda",
      '2': "terça",
      '3': "quarta",
      '4': "quinta",
      '5': "sexta",
      '6': "sábado",
      '7': "domingo"

  }.get(num, 'não encontrado')

num = input('Digite um número de 1 a 7: ')
print(diasemana(num))

"""## Exercício 16: Verifique se um número é par ou ímpar usando if ternário."""

num = int(input('Digite um número: '))
print('Par' if num % 2 == 0 else 'Ímpar')

#Verifique o(s) número(s) apresentados;
#Faça a divisão de cada um por 2;
#Se o resultado for um número inteiro diga que é par;
#Se for um número decimal, que é ímpar.

num = int(input('Digite um número: '))
if num % 2 == 0:
  print('Par')
else:
  print('Ímpar')

"""## Exercício 17: Verifique se um número é positivo ou negativo usando if ternário."""

num = int(input('Digite um número: '))
print('Positivo' if num > 0 else 'Negativo')

"""## Exercício 18: Retorne 'Adulto' se a idade for maior ou igual a 18, senão 'Menor de idade'."""

idade = int(input('Digite a idade: '))
print('Adulto' if idade >= 18 else 'Menor de Idade')



"""## Exercício 19: Verifique se um número é maior que 100 e retorne 'Grande' ou 'Pequeno'.

## Exercício 20: Retorne 'Aprovado' se a nota for maior ou igual a 7, senão 'Reprovado'.

## Exercício 21: Imprima os números de 1 a 10 usando um laço for.
"""

for i in range(1, 11):
  print(i)

"""## Exercício 22: Imprima os números pares de 1 a 20."""

for i in range(2, 21, 2):
  print(i)

"""## Exercício 23: Calcule a soma dos números de 1 a 100."""

print(sum(range(1, 101)))

cont = 0
for i in range(1, 100):

  cont += i
print(cont)

"""## Exercício 24: Imprima a tabuada do 5."""



"""## Exercício 25: Imprima os 10 primeiros números da sequência de Fibonacci.

## Exercício 26: Percorra uma string e imprima cada caractere.

## Exercício 27: Crie um programa que peça um número e imprima sua contagem regressiva até 0.

## Exercício 28: Crie um programa que solicite 5 números ao usuário e exiba a soma deles.

## Exercício 29: Imprima todas as vogais de uma string digitada pelo usuário.

## Exercício 30: Crie um programa que peça 5 números e exiba apenas os números pares.

## Exercício 31: Percorra uma lista de frutas e imprima cada uma.

## Exercício 32: Some todos os números de uma lista.

## Exercício 33: Multiplique cada número de uma lista por 2 e imprima o resultado.

## Exercício 34: Conte quantas palavras existem em uma lista de palavras.

## Exercício 35: Imprima cada letra de uma palavra separadamente.

## Exercício 36: Crie uma lista com 5 números e imprima o maior.

## Exercício 37: Crie uma lista e inverta a ordem dos elementos.

## Exercício 38: Crie uma lista com 5 nomes e remova o último nome.

## Exercício 39: Ordene uma lista de números.

## Exercício 40: Crie uma lista com 5 números e exiba apenas os pares.

## Exercício 41: Crie uma lista e adicione um novo elemento no final.

## Exercício 42: Verifique se um número existe dentro de uma lista.

## Exercício 43: Crie uma lista de números e calcule a média.

## Exercício 44: Crie uma lista de nomes e converta todos para maiúsculas.

## Exercício 45: Crie uma lista de números e remova os duplicados.

## Exercício 46: Crie um dicionário com nomes de alunos e suas notas e exiba a nota de um aluno específico.

## Exercício 47: Adicione um novo aluno e sua nota a um dicionário.

## Exercício 48: Remova um aluno do dicionário.

## Exercício 49: Percorra um dicionário e imprima suas chaves e valores.

## Exercício 50: Verifique se uma chave existe no dicionário.
"""